### ISSUE TITLE
Hippo Teeth (VTech, Sporty Time & Fun) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#18]
Hippo Teeth _(VTech, Sporty Time & Fun)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![hippo](https://cloud.githubusercontent.com/assets/852504/21082960/3c924434-bfac-11e6-927b-8040b427b6e2.png)

The left image should be fixed too.

**Comment by lasers** [comment]
@leiradel While you're looking at this, can you auto-trim/crop all handheld images just in case? Some other earlier handhelds I went through have (small) paddings... but this one is significant enough to file a minor bug report.

Extra padding is more noticeable in windowed mode than fullscreen mode. I will go through the rest of handheld games.

Also, can you share all pngs so I can clean it up (if any) and use it for the thumbnails?

**Comment by leiradel** [comment]
> @leiradel While you're looking at this, can you auto-trim/crop all handheld images just in case? Some other earlier handhelds I went through have (small) paddings... but this one is significant enough to file a minor bug report.

There's a minimum width so that the controller with button mappings that appear when you press select won't be cut off, so I can't change this.

> Also, can you share all pngs so I can clean it up (if any) and use it for the thumbnails?

Sorry, but no. The author shared the source code, including all assets, for me only, and I can't give them away. Also, the best thumbnails will be the ones with all cells lightened up, which isn't present in any image from the games, so it's better to print screen to create thumbnails.

**Comment by lasers** [comment]
Yeah. No problem. I took about 35 screenshots so far for `Named_Boxarts` and `Named_Snaps`. I can use GIMP to crop, resize, and clean up everything. All cells lit up.

**Comment by leiradel** [comment]
Fixed
