### ISSUE TITLE
Las Vegas (Bandai, LCD Game Digital) (Zoom)

### ISSUE THREAD

**Issue by lasers** [libretro/gw-libretro#20]
Las Vegas _(Bandai, LCD Game Digital)_
Press `SELECT` to play the game in zoomed mode.
Uh-oh. It does not look right. Things got cut off.

![lvb](https://cloud.githubusercontent.com/assets/852504/21083271/572d7cd6-bfb2-11e6-91cd-7ea2f7c6fbc2.png)

This is questionable.

**Comment by lasers** [comment]
@leiradel Should I keep going or stop making issues?

**Comment by leiradel** [comment]
> Things got cut off.

The zoom tries to enlarge the LCD only. Are you saying we should include the decorations? It may look better, yes.

> @leiradel Should I keep going or stop making issues?

Please do continue. I may not be able to keep up with them all since there are some other things requiring my attention, but if you open issues I'll be able to fix them later.

Thanks for the help.

**Comment by lasers** [comment]
Yes. In this case, it might be better to include top and bottom decorations.

Also, I also notice that some dual screen games does not zoom. It's not possible to bring both LCD together side-by-side?

In any case, I will keep making issues. Thanks for letting me know. I don't want to make unnecessary issues if you're going to look through them all from now on.

**Comment by leiradel** [comment]
> Yes. In this case, it might be better to include top and bottom decorations.

Will do.

> Also, I also notice that some dual screen games does not zoom. It's not possible to bring both LCD together side-by-side?

It is, and it was my intention to do so from the beginning, but it'll take some time to code it.

**Comment by lasers** [comment]
@leiradel I'm finished. Another thing... I legitimately played a `Donkey Kong Jr.` game and it sucks that if I messed up with a move, the game will either give me another chance or resets. `Rewinding` would be a nice feature to have for this short games so one could undo their moves.

Keep in mind that I will try all `Nintendo - G&W` games then I'm done.

**Comment by leiradel** [comment]
> if I messed up with a move, the game will either give me another chance or resets

It sounds like a bug. It should give you chances until you run out of lives.

> Rewinding would be a nice feature to have for this short games so one could undo their moves.

Yeah, G&W games don't support save states, because they are Lua programs, so I'd have to find some way to save the entire Lua universe. There's [Eris](https://github.com/fnuecke/eris), but I'll have to downgrade the Lua version used in the core which is 5.3.0.

**Comment by lasers** [comment]
Not a bug. I was talking about how games can give you more chances or end right there...Game over.... which I don't want to face in this... by undoing mistakes with rewind (thus finish the whole thing). Sorry for the confusion.

**Comment by leiradel** [comment]
Fixed
