### ISSUE TITLE
Instruction-layer priority issue on arm

### ISSUE THREAD

**Issue by ArcadeTV** [libretro/gw-libretro#41]
On my retropie setup I stumbled upon an issue:
When you hit the button for displaying the instructions, the sprites are displayed on top of the layer that shows the how-to-play-controller.
Thanks for all your work, been enjoying it very much.

**Comment by leiradel** [comment]
Is this still a problem? It has been fixed for some time now, so I think it's just a matter of updating the core in RetroPie.

**Comment by ArcadeTV** [comment]
I'm afraid yes. Did a rebuild from source but the issue remains.

**Comment by leiradel** [comment]
There was a small bug with the layer of the sprites, where the first sprite would get the highest priority layer. This was fixed [here](https://github.com/libretro/gw-libretro/commit/ae06261766487cca2742a0f60d7dc4877c6f6fc7).

I don't think that was the cause of the problem you're facing. Your problem was a known problem and was fixed [here](https://github.com/libretro/gw-libretro/commit/a749488027fa5b592afd74d5821d007a71b52907).

Could you test and see if the problem is solved? Thanks.

**Comment by ArcadeTV** [comment]
I testet it on my Ubuntu 16 setup last night and the issue was gone :)
Still need the rebuild and test on the PI.
THANKS!

**Comment by leiradel** [comment]
Awesome, thanks for the patience. Please re-open the issue if it's still a problem on the Pi.
